### ISSUE TITLE
About running the solver

### ISSUE THREAD

**Issue by RexYing** [pmontalb/PdeFiniteDifferenceSolver#1]
Hi thanks for sharing the PDE solver! I was trying to run cmake . and make.

However, the make command throws an error:

"/usr/bin/ld: cannot open output file PdeFiniteDifferenceSolver: Is a directory
collect2: error: ld returned 1 exit status
CMakeFiles/PdeFiniteDifferenceSolver.dir/build.make:109: recipe for target 'PdeFiniteDifferenceSolver' failed
make[2]: *** [PdeFiniteDifferenceSolver] Error 1
CMakeFiles/Makefile2:597: recipe for target 'CMakeFiles/PdeFiniteDifferenceSolver.dir/all' failed
make[1]: *** [CMakeFiles/PdeFiniteDifferenceSolver.dir/all] Error 2
Makefile:181: recipe for target 'all' failed"

do you know what might be the cause of this?
Thanks!

**Comment by pmontalb** [comment]
Are you able to run the unit tests? Have you initialized all the submodules? Is it an out-of-source build with cmake?

**Comment by RexYing** [comment]
I ran git submodule update --init --recursive so all modules should be there.

The steps I took is: git clone the repo; update submodules; run "cmake ." in root dir; run make in root dir.

I didn't run the unit tests. Now that I try to run it (./PdeUnitTests), all of them fail. Examples are:
" [ RUN      ] AdvectionDiffusion1DTests.ConstantSolutionNoTransportNoDiffusion
unknown file: Failure
C++ exception with description "Initialize returned 209" thrown in the test body.
[  FAILED  ] AdvectionDiffusion1DTests.ConstantSolutionNoTransportNoDiffusion (356 ms)"

Is it because the make command wasn't successful?

**Comment by RexYing** [comment]
The cmake version is:
cmake version 3.18.0
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by pmontalb** [comment]
What I would recommend is to do an out of source build:

cd project
mkdir cmake-build-debug
cmake ../
cd cmake-build-debug
make - j12

This should compile everything in debug mode

Also: do you have a valid Cuda compiler? If not you cannot run this (that's what it looks like reading the exception thrown in the unit tests)

**Comment by RexYing** [comment]
did you mean "cd cmake-build-debug" before "cmake ../"? when I did cmake ../ inside cmake-build-debug, somehow the makefile is still in root dir. When I execute make -j12 under project root, I get the following:
"/PdeFiniteDifferenceSolver/forge/src/backend/opengl/glfw/window.hpp:16:24: fatal error: GLFW/glfw3.h: No such file or directory".

Does that mean I need to install the glfw library? Would you recommend using cmake to install from this repo?
https://github.com/glfw/glfw

For Cuda compiler, I have nvcc 10.2. Is that fine?

**Comment by pmontalb** [comment]
Yes sorry, after you create the cmake-build directory, CD there, then run cmake ../

This project depends on forge, which has a bunch of dependencies to be installed, I think I've left some comments about what to install. It's just a bunch of sudo apt-get install

nvcc 10.2 is fine!

**Comment by RexYing** [comment]
Thanks! Where could I find the comments about what to install? I couldn't find it in Readme.
I could go into the forge dir and run make there, but if I could just do a bunch of sudo apt-get install that would be best!

**Comment by pmontalb** [comment]
It's in the main CMakeLists.txt line 9-17

**Comment by RexYing** [comment]
Thanks for pointing out! My make -j12 command succeeds after installing these requirements, and doing an out-of-source build:
"[100%] Linking CXX executable PdeUnitTests
[100%] Built target PdeUnitTests
[100%] Linking CXX executable PdeFiniteDifferenceSolver
[100%] Linking CXX executable PdeFiniteDifferenceSolverGpuPlot
[100%] Built target PdeFiniteDifferenceSolver
[100%] Built target PdeFiniteDifferenceSolverGpuPlot"

However, running ./PdeUnitTests gives me the following error:
"[ RUN      ] AdvectionDiffusion1DTests.ConstantSolutionNoTransportNoDiffusion
unknown file: Failure
C++ exception with description "Initialize returned 209" thrown in the test body.
[  FAILED  ] AdvectionDiffusion1DTests.ConstantSolutionNoTransportNoDiffusion (482 ms)"

Wonder if you have seen it before? Also running "python pdeRunner.py" throws an IO error: seems that the program PdeFiniteDifferenceSolver didn't output files like wave2d.cl to be read by the python file.

**Comment by pmontalb** [comment]
Can you run CLTests? This 109 error seems to be a cuda error, the kernel code cannot run on your gpu. I think I've hard-coded the computation capability to 6.1, and if you have an older GPU that doesn't support this, the kernels won't run.

What gpu do you have?

**Comment by RexYing** [comment]
I'm running it on a multi-gpu machine. Each GPU is RTX 2080 (11G memory).
Driver Version: 440.33.01    CUDA Version: 10.2
They seem to be updated.

How do I run CLTests? Is it included in the repo?

I also find that during cmake ../, there are warnings. Not sure if they are related?
-- Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY) 
CMake Warning (dev) in CudaLight/CudaLightKernels/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.
