### ISSUE TITLE
Steps for usage

### ISSUE THREAD

**Issue by xiang-tao** [pmontalb/PdeFiniteDifferenceSolver#2]
Hello, I am a graduate student, and I want to use C++ to solve partial differential equations. When I was troubled by this, I saw the code you wrote, so I plan to write C++ on your framework The program solves partial differential equations, but as far as I am concerned, my understanding of c++ and cmake is very shallow. Can you tell me how to use your code framework? Or what are the steps to use your code framework?thanks.

**Comment by pmontalb** [comment]
If you've never used cmake and are not familiar with how CUDA works I don't recommend to use this library. The calculations are performed in CUDA, whilst the infrastructure is written in C++.

What I can suggest is for your project to take inspiration from the CUDA calculations (found in PdeFiniteDifferenceKernels)

**Comment by xiang-tao** [comment]
Thank you for your answer, it is very helpful to me.
